export const GOOGLE_AUTOCOMPLETE_CLIENT_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_AUTOCOMPLETE_CLIENT_KEY;
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const STRIPE_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
export const SERVICE_FEE = 0.5;
